name: Checkout One Bug Report
description: >
  Use this form to file a bug report against the Checkout One support in the POS App. If you have logs,
  screenshots or videos, create the issue then edit the description to add them.
title: ''
labels: ["C1 Triage"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report bugs found in the Checkout One support in the POS App.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce
      placeholder: |
        1. Got to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what you observed happening.
    validations:
      required: true
  - type: input
    id: shop
    attributes:
      label: Shop name or ID
    validations:
      required: true
  - type: input
    id: build
    attributes:
      label: Version and build
      description: Version and build of the POS App e.g. V8.7.1 Build 2029. Look Settings -> Support -> View device information
    validations:
      required: true
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating system
      multiple: true
      description: Which operating system were you using? Choose Android for POS Go.
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Which device were you using?
      multiple: true
      options:
        - Android Emulator
        - Android Phone
        - Android Tablet
        - iPhone
        - iPad
        - iPhone Simulator
        - iPad Simulator
        - POS Go
