-- Show pending keybinds
-- https://github.com/folke/which-key.nvim
return {
  {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
      preset = 'modern',
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = '<Up> ',
          Down = '<Down> ',
          Left = '<Left> ',
          Right = '<Right> ',
          C = '<C-…> ',
          M = '<M-…> ',
          D = '<D-…> ',
          S = '<S-…> ',
          CR = '<CR> ',
          Esc = '<Esc> ',
          ScrollWheelDown = '<ScrollWheelDown> ',
          ScrollWheelUp = '<ScrollWheelUp> ',
          NL = '<NL> ',
          BS = '<BS> ',
          Space = '<Space> ',
          Tab = '<Tab> ',
          F1 = '<F1>',
          F2 = '<F2>',
          F3 = '<F3>',
          F4 = '<F4>',
          F5 = '<F5>',
          F6 = '<F6>',
          F7 = '<F7>',
          F8 = '<F8>',
          F9 = '<F9>',
          F10 = '<F10>',
          F11 = '<F11>',
          F12 = '<F12>',
        },
      },
      sort = { 'alphanum' },
      spec = {
        { '<leader>a', group = 'Apple development' },
        { '<leader>ad', group = 'Apple debugging' },
        { '<leader>c', group = 'Code', mode = { 'n', 'x' } },
        { '<leader>C', group = 'CodeCompanion', mode = { 'n' } },
        { '<leader>d', group = 'Debugger' },
        { '<leader>f', group = 'Find' },
        { '<leader>G', group = 'Git' },
        { '<leader>l', group = 'Language Tools' },
        { '<leader>r', group = 'Rename' },
        { '<leader>s', group = 'Selections' },
        { '<leader>T', group = 'Terminal' },
        { '<leader>t', group = 'Tests' },
        { '<leader>w', group = 'Workspace' },
        { '<leader>X', group = 'Trouble Lists' },
      },
      win = {
        border = 'rounded',
      },
    },
  },
}
